# SITE SETTINGS
title: WIMANET - Wildlife malaria network
# author: 
baseurl: "/wimanet" 

# SOCIAL PROFILES
social:
#  email: wimanet.science@gmail.com
#  twitter: @wimanet.science
#  github: github.io/wimanet.science

# THEME SETTINGS
theme: minima # Fallback theme
remote_theme: peterdesmet/petridish@3.0
posts_on_home: 1
tweets_on_home: true
archive_permalink: /news/
github_edit: true
# logo: 
colors:
  links: "#93c243"
  banner: "#93c243"
  footer: "#513266"

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      type: "posts"
    values:
      permalink: "/news/:year/:slug/"
